export const modalStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    backdropFilter: 'blur(6px)', // Slight blur for a modern industrial feel
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    animation: 'modalFadeIn 0.2s ease-out',
  },
  content: {
    backgroundColor: '#0f0f0f',
    border: '1px solid #2a2a2a',
    padding: '32px',
    borderRadius: '4px',
    maxWidth: '420px',
    width: '90%',
    textAlign: 'center',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    position: 'relative',
    overflow: 'hidden',
  },
  // Decorative "caution" stripe at the top
  accentBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#f39c12',
  },
  title: {
    color: '#fff',
    fontSize: '14px',
    letterSpacing: '2px',
    margin: '10px 0 15px 0',
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  message: {
    color: '#888',
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 30px 0',
  },
  actions: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'center',
  },
  confirmBtn: {
    backgroundColor: '#e74c3c',
    color: '#fff',
    border: 'none',
    padding: '10px 24px',
    borderRadius: '2px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '1px',
    transition: 'all 0.2s ease',
  },
  cancelBtn: {
    backgroundColor: 'transparent',
    color: '#666',
    border: '1px solid #333',
    padding: '10px 24px',
    borderRadius: '2px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 700,
    transition: 'all 0.2s ease',
  },
};