export const styles = {
  wrapper: {
    minHeight: '100vh',
    backgroundColor: '#0f0f0f',
    backgroundImage: 'radial-gradient(circle at 1px 1px, #1a1a1a 1px, transparent 1px)',
    backgroundSize: '20px 20px',
    color: '#e0e0e0',
  },
  container: {
    padding: '40px max(5vw, 20px)',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: '40px',
    paddingBottom: '20px',
    borderBottom: '1px solid #222',
  },
  title: {
    margin: 0,
    fontSize: '24px',
    fontWeight: 600,
    color: '#fff',
    letterSpacing: '1px',
  },
  subtitle: {
    margin: '8px 0 0',
    fontSize: '11px',
    color: '#f39c12',
    letterSpacing: '3px',
    textTransform: 'uppercase',
    opacity: 0.8,
  },
  addBtn: {
    backgroundColor: '#f39c12',
    color: '#000',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '11px',
    letterSpacing: '1px',
    fontWeight: 700,
    transition: 'all 0.2s ease',
  },
  cancelBtn: {
    backgroundColor: '#333',
    color: '#fff',
  },
  error: {
    color: '#ff6b6b',
    fontSize: '12px',
    padding: '12px 20px',
    marginBottom: '24px',
    backgroundColor: 'rgba(255, 107, 107, 0.05)',
    border: '1px solid rgba(255, 107, 107, 0.2)',
    borderRadius: '4px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorClose: {
    background: 'none',
    border: 'none',
    color: '#ff6b6b',
    cursor: 'pointer',
    fontSize: '18px',
  },
  formContainer: {
    animation: 'slideDown 0.3s ease-out',
  },
  form: {
    backgroundColor: '#111',
    border: '1px solid #222',
    padding: '30px',
    marginBottom: '40px',
    borderRadius: '8px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.5)',
  },
  formHeader: {
    marginBottom: '25px',
  },
  formTitle: {
    margin: '0 0 25px 0',
    fontSize: '13px',
    color: '#f39c12',
    letterSpacing: '1.5px',
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '20px',
    marginBottom: '25px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '9px',
    color: '#666',
    letterSpacing: '1px',
    fontWeight: 600,
  },
  input: {
    padding: '12px',
    backgroundColor: '#050505',
    border: '1px solid #333',
    borderRadius: '4px',
    color: '#fff',
    fontSize: '13px',
    transition: 'border-color 0.2s',
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    borderTop: '1px solid #222',
    paddingTop: '20px',
  },
  submitBtn: {
    backgroundColor: '#f39c12',
    color: '#000',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '11px',
    letterSpacing: '1px',
    fontWeight: 700,
    transition: 'all 0.2s ease',
  },
  loaderLine: {
    height: '2px',
    width: '100%',
    backgroundColor: '#f39c12',
    overflow: 'hidden',
    position: 'relative',
  },
  tableWrapper: {
    overflowX: 'auto',
    borderRadius: '8px',
    border: '1px solid #222',
    backgroundColor: '#111',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '16px 20px',
    textAlign: 'left',
    backgroundColor: '#151515',
    color: '#888',
    fontSize: '10px',
    letterSpacing: '1px',
    fontWeight: 600,
    textTransform: 'uppercase',
    borderBottom: '1px solid #222',
  },
  tr: {
    borderBottom: '1px solid #1a1a1a',
    transition: 'background 0.15s ease',
  },
  td: {
    padding: '16px 20px',
    color: '#bbb',
    fontSize: '13px',
  },
  idBadge: {
    backgroundColor: '#222',
    padding: '2px 6px',
    borderRadius: '3px',
    fontSize: '10px',
    fontFamily: 'monospace',
    color: '#888',
  },
    tdRight: {
        padding: '16px 20px',
        textAlign: 'right',
        width: '1%', 
        whiteSpace: 'nowrap',
    },
    actionGroup: {
        display: 'flex',
        gap: '24px', 
        justifyContent: 'flex-end',
        alignItems: 'center', 
    },
  editBtn: {
    background: 'none',
    border: 'none',
    color: '#f39c12',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    padding: '4px 0',
    transition: 'all 0.2s ease',
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#666',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    padding: '4px 0',
    transition: 'all 0.2s ease',
  },
  emptyState: {
    padding: '60px',
    textAlign: 'center',
    color: '#444',
    fontSize: '12px',
    letterSpacing: '2px',
  }
};